module.exports = {
  HOUSING_APPROVED: 'HOUSING_APPROVED',
  HOUSING_REJECTED: 'HOUSING_REJECTED',
  SHELTER_APPROVED: 'SHELTER_APPROVED',
  SHELTER_REJECTED: 'SHELTER_REJECTED',
  ADOPTION_APPROVED: 'ADOPTION_APPROVED',
  ADOPTION_REJECTED: 'ADOPTION_REJECTED',
  PET_RETURN_CREATED: 'PET_RETURN_CREATED',
  PET_RETURN_UPDATED: 'PET_RETURN_UPDATED',
};
