#!/usr/bin/env python3
import json
import os
import sys

def main():
    raw = os.environ.get("META", "{}")
    try:
        d = json.loads(raw)
    except Exception:
        d = {}

    def f(key, default="N/A"):
        v = d.get(key)
        return str(v) if v is not None else default

    job_status = os.environ.get("JOB_STATUS", "failure")
    status_badge = "✅ SUCCESS" if job_status == "success" else "❌ FAILED"

    duration_ms = d.get("duration_ms")
    if duration_ms is not None:
        try:
            ms = int(duration_ms)
            duration_str = f"{ms / 1000:.1f}s ({ms}ms)"
        except (ValueError, TypeError):
            duration_str = str(duration_ms)
    else:
        duration_str = "N/A"

    run_url = os.environ.get("RUN_URL", "")
    git_ref = os.environ.get("GIT_REF", "N/A")
    actor = os.environ.get("ACTOR", "N/A")

    lines = [
        "## 🚀 Deployment Center",
        "",
        "### Current Deployment",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Status**         | {status_badge} |",
        f"| **Action**         | `{f('action')}` |",
        f"| **Git Ref**        | `{git_ref}` |",
        f"| **Ref Type**       | {f('ref_type')} |",
        f"| **Commit SHA**     | `{f('short_sha')}` |",
        f"| **Commit Message** | {f('commit_message')} |",
        f"| **Health Check**   | {f('health_result')} |",
        f"| **Duration**       | {duration_str} |",
        f"| **Deploy Time**    | {f('deployed_at')} |",
        f"| **Deployed By**    | `{actor}` |",
        f"| **Run**            | [View Logs]({run_url}) |",
        "",
        "---",
        f"_Generated by [Deploy Version]({run_url}) workflow_",
    ]

    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
    else:
        print("\n".join(lines))

if __name__ == "__main__":
    main()
